---
- name: Default server
  hosts: webservers
  become: true
  tasks:
    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      notify: Upgrade all packages

    - name: uninstall nginx
      ansible.builtin.apt:
        pkg: nginx
        state: absent
      notify: Stop nginx

  handlers:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true

    - name: Stop nginx
      ansible.builtin.systemd_service:
        unit: nginx
        state: stopped
        enabled: true

    - name: Restart nginx
      ansible.builtin.systemd_service:
        unit: nginx
        state: restarted
        enabled: true
