---
- name: Install default Apache Web Server
  hosts: all
  become: true

  tasks:
  - name: Install Apache WebServer
    apt: name=httpd state=latest

  - name: Start Apache and Enable it on the every boot
    service: name=httpd state=started enabled=yes

