---
- name: Prepare server
  hosts: webservers
  become: true
  tasks:
    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      notify: Upgrade all packages

    - name: install nginx
      ansible.builtin.apt:
        pkg: nginx
        state: present
      notify: Start nginx

  handlers:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true

    - name: Start nginx
      ansible.builtin.systemd_service:
        unit: nginx
        state: started
        enabled: true

    - name: Restart nginx
      ansible.builtin.systemd_service:
        unit: nginx
        state: restarted
        enabled: true
