---
# tasks file for deploy_nginx

- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  notify: Upgrade all packages

- name: install nginx
  ansible.builtin.apt:
    pkg: nginx
    state: present
  notify: Start nginx

- name: create configuration file
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: create second configuration file
  template:
    src: nginx_vhosts.j2
    dest: /etc/nginx/conf.d/{{ fqdn }}.conf
  notify: Restart nginx
